"""STATUS.md writer — human + future-agent readable progress log.

The agent harness calls `record(...)` as it works so STATUS.md always reflects
the current task, a short todo, and the last few actions. A fresh Claude window
can read STATUS.md (and logs/agent.log) to resume without re-deriving context.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import LOGS_DIR, STATUS_FILE
from .logging_config import get_logger

log = get_logger(__name__)

_ACTIVITY = LOGS_DIR / "activity.jsonl"
_MAX_RECENT = 15


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def record(event: str, detail: str = "", *, current_task: str | None = None,
           todo: list[str] | None = None) -> None:
    """Append an activity event and re-render STATUS.md."""
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    entry: dict[str, Any] = {"ts": _now(), "event": event, "detail": detail}
    if current_task is not None:
        entry["current_task"] = current_task
    if todo is not None:
        entry["todo"] = todo
    with _ACTIVITY.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")
    log.info("status: %s %s", event, detail)
    _render()


def _recent() -> list[dict[str, Any]]:
    if not _ACTIVITY.exists():
        return []
    lines = _ACTIVITY.read_text(encoding="utf-8").strip().splitlines()
    out = []
    for line in lines:
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


def _render() -> None:
    events = _recent()
    current_task = next(
        (e["current_task"] for e in reversed(events) if e.get("current_task")), "idle"
    )
    todo = next((e["todo"] for e in reversed(events) if e.get("todo")), [])
    recent = events[-_MAX_RECENT:]

    lines = [
        "# STATUS",
        "",
        "> Auto-generated by the agent harness. A fresh session can read this file",
        "> plus `logs/agent.log` to resume. Do not hand-edit; it is overwritten.",
        "",
        f"- **Updated:** {_now()}",
        f"- **Current task:** {current_task}",
        "",
        "## Todo",
    ]
    lines += [f"- [ ] {t}" for t in todo] or ["- (none)"]
    lines += ["", "## Recent activity"]
    lines += [f"- `{e['ts']}` **{e['event']}** — {e.get('detail', '')}" for e in reversed(recent)] or [
        "- (none)"
    ]
    Path(STATUS_FILE).write_text("\n".join(lines) + "\n", encoding="utf-8")
